sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=fiwoo-platform/ubuntu_16.04-tomcat
    - MICROSERVICES="Data-Visualization eureka-registry user-auth user-management"
    - TOMCAT_VERSION=8.5.24

script:
  - docker build -t $DOCKER_IMAGE .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      DOCKER_IMAGE_COMMIT=$(git log -1 --pretty=format:'%h');
      DOCKER_IMAGE_TIMESTAMP=$(docker inspect -f '{{ .Created }}' ${DOCKER_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g');
      docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push $DOCKER_IMAGE:latest;
      docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;

      for micoservice in "$MICROSERVICES"; do
        rm -rf src;
        git clone https://github.com/fiwoo-platform/${microservice}.git src;

        docker run --rm -v $PWD/src:/src --entrypoint=/bin/bash $DOCKER_IMAGE:latest -c "source /assets/bin/fiwoo-platform.functions;build-war-file";

        docker run --rm -v $PROJECT_DIR/src/target:/src/target --entrypoint=/bin/bash $DOCKER_IMAGE:latest -c 'jar xvf /src/target/*.war';

        rm -f /src/target/*.war;
        mkdir -p assets/opt/apache-tomcat-${TOMCAT_VERSION}/webapps/ROOT/;
        rsync -Pavz --delete src/target/ assets/opt/apache-tomcat-${TOMCAT_VERSION}/webapps/ROOT/;
        docker build -t fiwoo-platform/$microservice:latest .;
        docker tag $microservice:latest fiwoo-platform/$microservice:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
        docker push $microservice:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
        docker push $microservice:latest;
      done;
    fi

notifications:
  email:
    recipients:
      - emergya-integration-github@emergya.com
    on_success: always
    on_failure: always
