sudo: required

language: bash

services:
  - docker

env:
  global:
    - DOCKER_IMAGE=fiwoo/ubuntu_16.04-tomcat
    - MICROSERVICES="Data-Visualization eureka-registry user-auth user-management"
    - TOMCAT_VERSION=8.5.24

script:
  - docker build -t $DOCKER_IMAGE .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      DOCKER_IMAGE_COMMIT=$(git log -1 --pretty=format:'%h');
      DOCKER_IMAGE_TIMESTAMP=$(docker inspect -f '{{ .Created }}' ${DOCKER_IMAGE}|awk -F':' '{print $1$2}'|sed 's%-\|T%%g');
      docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
      docker push $DOCKER_IMAGE:latest;
      docker push $DOCKER_IMAGE:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;

      set -x;
      for microservice in $(echo $MICROSERVICES); do
        sudo rm -rf ${microservice};
        git config --global url."https://github.com/".insteadOf git@github.com:;
        git clone https://github.com/fiwoo-platform/${microservice}.git ${microservice};

        docker run --rm -v $PWD/${microservice}/src:/src -e ENVIRONMENT=build --entrypoint=/bin/bash $DOCKER_IMAGE:latest -c "source /assets/bin/fiwoo-platform.functions;build-war-file";

        docker run --rm -v $PWD/${microservice}/src/target:/src/target --entrypoint=/bin/bash $DOCKER_IMAGE:latest -c 'jar xvf /src/target/*.war';

        sudo rm -f $PWD/${microservice}/src/target/*.war;
        sudo rm -rf assets/opt/apache-tomcat-${TOMCAT_VERSION}/webapps/ROOT;
        mkdir -p assets/opt/apache-tomcat-${TOMCAT_VERSION}/webapps/ROOT/;
        rsync -Pavz --delete $PWD/${microservice}/src/target/ assets/opt/apache-tomcat-${TOMCAT_VERSION}/webapps/ROOT/;
        docker build -t fiwoo/$microservice:latest .;
        docker tag $microservice:latest fiwoo/$microservice:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
        docker push fiwoo/$microservice:$DOCKER_IMAGE_TIMESTAMP-$DOCKER_IMAGE_COMMIT;
        docker push fiwoo/$microservice:latest;
      done;
    fi

notifications:
  email:
    recipients:
      - emergya-integration-github@emergya.com
    on_success: always
    on_failure: always
